services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        volumes:
            - ./app/:/var/www/app/
        ports:
            - 8001:80
        networks:
            - bank
            
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        environment:
            APP_ENV: dev
            DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}?serverVersion=5.7
        volumes:
            - ./app/:/var/www/app/
        networks:
            - bank
        depends_on:
            - mysql

    mysql:
        image: mysql
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - bank
        
networks:
    bank: