FROM php:7.4.30-fpm

#add php extensions lib
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions pdo_mysql

WORKDIR /app
CMD ["php-fpm"]
